# Generated by Django 4.2 on 2025-02-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_delete_personaltoken'),
        ('root', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
